.TH "MYHEAD" "1" "2018\-04\-04" "myhead v1.0.0" "execjosh"
.SH NAME
\fBmyhead\fR \- a clone of \fBhead(1)\fR implemented in go
.SH SYNOPSIS
\fBmyhead\fR [\fB\-n\fR=\fICOUNT\fR] [\fIFILE\fR]...
.SH DESCRIPTION
.PP
This is an implementation of \fBhead(1)\fR in go for educational purposes.
.PP
Prints first \fICOUNT\fR (or 10 if not specified) lines of each \fIFILE\fR to
stdout.  If no \fIFILE\fR is specified, reads from stdin.  If multiple files are
specified, displays header (``==> \fIFILE\fR <=='') before each file's output.
.SH EXAMPLES
.PP
myhead
.PP
myhead /path/to/file
.PP
myhead /path/to/file1 /path/to/file2 /path/to/file3
.PP
myhead -n=1 /path/to/file
.PP
myhead -n=1 /path/to/file1 /path/to/file2
.PP
cat /path/to/file | myhead
.PP
cat /path/to/file | myhead -n=1
.SH DIAGNOSTICS
Exits 0 on success; otherwise, exits 1.
.SH AUTHOR
Written by execjosh
.SH COPYRIGHT
Copyright \(co 2018 execjosh
.br
MIT License
.SH SEE ALSO
.PP
\fBhead(1)\fR

